### ISSUE TITLE
problem with simulated lightcurve

### ISSUE THREAD

**Issue by antoinech13** [phoebe-project/phoebe2-docs#18]
hello, i have a problem which was not present 1 or 2 mounths ago. Indeed, i try to prepare simulated lightcurves. I already wrote  a code with phoebe which allowed me to do that but since little time that not function well anymore.

`import phoebe
b=phoebe.default_binary()
b.set_value('teff', component='secondary', value=5000)
b.add_dataset('lc', times=phoebe.linspace(0,1000,4800),dataset='mylc')
b.set_value('pblum_mode', value='decoupled')

P=74

b.get_parameter(qualifier='period', component= 'binary', context='component').set_value(P)`

![fig1](https://user-images.githubusercontent.com/57111263/88387857-b05dd180-cdb3-11ea-872b-c7bdeb8825ae.png)

Here the code function more or less well. The problem really appear when i try to set mass.

`import phoebe
b=phoebe.default_binary()
b.set_value('teff', component='secondary', value=5000)
b.add_dataset('lc', times=phoebe.linspace(0,1000,4800),dataset='mylc')
b.set_value('pblum_mode', value='decoupled')

P=74
M_primar = 3

b.get_parameter(qualifier='period', component= 'binary', context='component').set_value(P)
b.flip_constraint('mass@primary', solve_for='sma@binary')  
b.get_parameter(qualifier='mass', component= 'primary', context='component').set_value(M_primar)`

here the result:

![fig2](https://user-images.githubusercontent.com/57111263/88388053-0cc0f100-cdb4-11ea-8edc-f8937128be24.png)

as you can see i have variability on the depth of transits. I dont want this variability. how can i leave it?

**Comment by aprsa** [comment]
This looks like a sampling issue to me. You are using a linspace between 0 and 1000 with 4800 steps, which doesn't sample eclipses finely enough. Try increasing 4800 and see if that solves your issue?

**Comment by antoinech13** [comment]
thank you for your reply. 

Yes i thought about that too and i also tried it with 10 000 points. The problem is still the same.

**Comment by kecnry** [comment]
This is indeed a sampling issue which is exaggerated by the change in the semi-major axis caused by your change in mass (you can see that the apparent depths are different in the first plot as well).  As far as I can tell, the underlying model is fine, its just the sampling and plotting that is showing an _apparent_ change in eclipse depth because you're missing the bottoms of the eclipses.  Increasing to 10000 points didn't help you because your orbital period is 74 days and linspace includes both endpoints - meaning that you're still not sampling each cycle at the same phases.

The easiest fix from your end is to set your sampling as an integer of your orbital period.  For example, to sample each cycle with 500 points you could instead set times to `phoebe.arange(0,1000,74./500)` (where the last argument is now the step-size in days).  This will ensure that each cycle is sampled in the same phases and you then get the following:
![Figure](https://user-images.githubusercontent.com/877591/88399415-d45dea80-cd94-11ea-9c76-ff7e4016103d.png)

If you have actual observations or are happy with a single cycle, I would suggest using [compute_phases](http://phoebe-project.org/docs/latest/tutorials/compute_times_phases) instead to get around this issue entirely.  That way you don't need to adjust the time-sampling for a change in orbital period.

It does surprise me though if you say this has changed recently.  Did an update in phoebe cause the change?  If so, can you let me know which version you had before and which version you have now so I can try to reproduce that and figure out what caused the change?

As a side note - be careful with using `pblum_mode='decoupled'`.  There are very few rare cases where that is actually what you want for a physical model.  See [this tutorial](http://phoebe-project.org/docs/latest/tutorials/pblum) for more details

**Comment by antoinech13** [comment]
ok i find the solution. Yes it's a sampling problem but increase the number of point take really long calculation time. The best way is to insure that they are all time the same number of points every simulation days.
